name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set short SHA
        id: short_sha_step
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: andreavix/python-app:${{ steps.short_sha_step.outputs.short_sha }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - 
        name: argocd cli install
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd 
          sudo mv ./argocd /usr/local/bin/argocd

      - 
        name: argocd app sync
        shell: bash
        run: | 
          argocd login argocd-server.argocd --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASS  }}
          argocd app sync python-app